### ISSUE TITLE
Will pre-trained models be released?

### ISSUE THREAD

**Issue by davislf2** [XuezheMax/fairseq-apollo#2]
Hi @XuezheMax, thank you for this impressive paper and repo. I saw [LUNA BERT model has released code base](https://github.com/XuezheMax/fairseq-apollo/tree/master/fairseq/models/luna_bert), and I am interested in will you release all your pre-trained models (e.g. Luna-16, Luna-128, Luna-128 BERT, Luna-256) in the near future? Thanks.

**Comment by XuezheMax** [comment]
Hi,

Thanks for your interests. We are still cleaning our code and will release a well-organized version with all the pre-trained models soon.

**Comment by XuezheMax** [comment]
@davislf2 Now the
