### ISSUE TITLE
What is the loss for P?

### ISSUE THREAD

**Issue by JingyunLiang** [XuezheMax/fairseq-apollo#4]
After the last layer, where does P go?

**Comment by XuezheMax** [comment]
In encoder-decoder model, P from the encoder is used in decoder. For encoder-only model on classification tasks, we do not use P in the loss but only the cls token.

**Comment by shawnkx** [comment]
On LRA benchmark, we have tried to use the output of P as the sentence representation for classification. See table 3 in our paper for more details.

**Comment by JingyunLiang** [comment]
Thanks for your clarification.
