### ISSUE TITLE
Scripts

### ISSUE THREAD

**Issue by niumanar** [XuezheMax/fairseq-apollo#6]
Hi, I'm interested in reproducing the results in Section 4.1 and 4.2. Could you please upload the scripts/documentation for this? Thank you!

**Comment by XuezheMax** [comment]
You mean LRA and WMT for Luna? We will release the scripts and models soon.

**Comment by niumanar** [comment]
Yes, I'm interested in all applications of LUNA including LRA, MLM/NLU and NMT. Looking forward to the scripts and models!

**Comment by XuezheMax** [comment]
The scripts for LRA and NMT are ready. We will release our pre-trained models soon.
