### ISSUE TITLE
Questions about WMT14 EN-DE dataset.

### ISSUE THREAD

**Issue by Doraemonzzz** [XuezheMax/fairseq-apollo#8]
Thank you for your wonderful work, there is a question about WMT 14 EN-DE dataset. I can't find the code of RFA on WMT 14 EN-DE dataset. Could you please release them? Since I have tried to train RFA on WMT 14 EN-DE dataset, but it cannot converge, thanks.

**Comment by XuezheMax** [comment]
Sorry for the late reply. Please go to our official repo for more details. We provide the scripts for process MT data:
https://github.com/facebookresearch/mega/blob/main/examples/mega/README.mt.md
