### ISSUE TITLE
MEGA LM scripts/readme

### ISSUE THREAD

**Issue by NtaylorOX** [XuezheMax/fairseq-apollo#9]
When trying to access instructions or the readme for the LM experiment under "Experiments" here:  https://github.com/XuezheMax/fairseq-apollo/tree/master/examples/mega. The link for the Language Modelling experiment is broken or does not exist

https://github.com/XuezheMax/fairseq-apollo/blob/master/examples/mega/README.lm.md 

Any update would be appreciated.

Thanks

**Comment by XuezheMax** [comment]
Hi,
Thanks for your comments. The LM part is still under the internal review of Meta AI Research. Once it is finished, please checkout the official repo for Mega: https://github.com/facebookresearch/mega

**Comment by XuezheMax** [comment]
@NtaylorOX Now the official repo of Mega is publicly online:
https://github.com/facebookresearch/mega
